{{- range $svcName, $svc := .Values.services }}
{{- if and $svc.enabled (ne (toString (dig "createServiceAccount" "true" $svc)) "false") }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $svcName }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $svcName }}
{{- end }}
{{- end }}
