stages:
  - build
  - gitops

default:
  tags:
    - docker

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  GITOPS_BRANCH: "main"
  # Online Boutique 서비스 목록 (공백 구분, sh 호환)
  BOUTIQUE_SERVICES: "adservice cartservice checkoutservice currencyservice emailservice frontend loadgenerator paymentservice productcatalogservice recommendationservice shippingservice"

# 1) 이미지 빌드 + GitLab Registry 푸시
build_boutique_images:
  stage: build
  image: docker:24.0.5-cli
  services:
    - name: docker:24.0.5-dind
      alias: docker
      # 사설/랩 환경에서 필요하면 유지
      command: ["--insecure-registry=192.168.10.47:5050"]
  before_script:
    - apk add --no-cache git
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - export IMAGE_TAG="${CI_COMMIT_SHORT_SHA}"
    - |
      set -eu

      # 시작 전에 한 번 정리 (이전 찌꺼기 방지)
      docker builder prune -af || true

      for svc in $BOUTIQUE_SERVICES; do
        SVC_ROOT="./src/${svc}"

        if [ ! -d "$SVC_ROOT" ]; then
          echo "❌ 서비스 디렉터리 없음: $SVC_ROOT"
          exit 1
        fi

        DOCKERFILE_PATH="$(find "$SVC_ROOT" -type f -name Dockerfile | head -n1)"
        if [ -z "$DOCKERFILE_PATH" ]; then
          echo "❌ Dockerfile 없음: $SVC_ROOT"
          exit 1
        fi

        BUILD_CTX="$(dirname "$DOCKERFILE_PATH")"

        echo "==> Build & Push: ${CI_REGISTRY_IMAGE}/${svc}:${IMAGE_TAG}"
        echo "    Dockerfile: $DOCKERFILE_PATH"
        echo "    Context   : $BUILD_CTX"

        docker build --progress=plain --pull -f "$DOCKERFILE_PATH" -t "${CI_REGISTRY_IMAGE}/${svc}:${IMAGE_TAG}" "$BUILD_CTX"
        docker push "${CI_REGISTRY_IMAGE}/${svc}:${IMAGE_TAG}"

        # ✅ 푸시 후 즉시 정리 (디스크 부족 방지)
        docker image rm "${CI_REGISTRY_IMAGE}/${svc}:${IMAGE_TAG}" || true
        docker builder prune -af || true

        # (선택) 현재 사용량 확인 로그
        docker system df || true
      done
    - printf "IMAGE_TAG=%s\n" "$IMAGE_TAG" > build.env
  artifacts:
    reports:
      dotenv: build.env

# 2) gitops-repo의 kustomization.yaml 이미지 태그 갱신
update_gitops_tags:
  stage: gitops
  image: alpine:3.20
  needs: ["build_boutique_images"]
  resource_group: boutique-gitops-update
  before_script:
    - apk add --no-cache git curl ca-certificates
    - curl -fsSL https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -o /usr/local/bin/yq
    - chmod +x /usr/local/bin/yq
    # 임시 우회(사설 인증서 환경). 나중에 CA 신뢰 설정되면 제거 권장
    - git config --global http.sslVerify false
  script:
    - |
      set -eu
      : "${GITOPS_PUSH_USER:?missing}"
      : "${GITOPS_PUSH_TOKEN:?missing}"
      : "${GITOPS_REPO_URL:?missing}"
      : "${IMAGE_TAG:?missing}"

      AUTH_URL="$(echo "$GITOPS_REPO_URL" | sed "s#https://#https://${GITOPS_PUSH_USER}:${GITOPS_PUSH_TOKEN}@#")"

      git clone "$AUTH_URL" /tmp/gitops
      cd /tmp/gitops

      FILE="apps/boutique/overlays/dev/kustomization.yaml"
      test -f "$FILE"

      UPSTREAM_PREFIX="us-central1-docker.pkg.dev/google-samples/microservices-demo"

      for svc in $BOUTIQUE_SERVICES; do
        MATCH_NAME="${UPSTREAM_PREFIX}/${svc}"
        NEW_NAME="${CI_REGISTRY_IMAGE}/${svc}"
        NEW_TAG="${IMAGE_TAG}"

        MATCH_NAME="$MATCH_NAME" NEW_NAME="$NEW_NAME" NEW_TAG="$NEW_TAG" \
        yq -i '
          (.images[] | select(.name == strenv(MATCH_NAME))).newName = strenv(NEW_NAME) |
          (.images[] | select(.name == strenv(MATCH_NAME))).newTag  = strenv(NEW_TAG)
        ' "$FILE"
      done

      git config user.name "gitlab-ci"
      git config user.email "gitlab-ci@local"

      git add "$FILE"
      if git diff --cached --quiet; then
        echo "변경 사항 없음"
        exit 0
      fi

      git commit -m "boutique: bump images to ${IMAGE_TAG} (${CI_COMMIT_SHORT_SHA})"
      git push origin "HEAD:${GITOPS_BRANCH}"
  rules:
    - if: '$CI_COMMIT_BRANCH'