apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/descheduler/
      chart: descheduler
      targetRevision: 0.31.0
      helm:
        valueFiles:
          - $values/apps/descheduler/values.yaml
    - repoURL: https://<GITLAB_IP>/root/gitops-repo.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
